#index:
#    path: /
#    controller: App\Controller\DefaultController::index

inscription:
    resource: 'routes/inscription.yaml'
    prefix: '/inscription'

profil:
    resource: 'routes/profil.yaml'
    prefix: '/profil'

home:
    resource: 'routes/home.yaml'
    prefix: '/'

game:
    resource: 'routes/game.yaml'
    prefix: '/game'

admin:
    resource: 'routes/admin.yaml'
    prefix: '/admin'

connexion:
    resource: 'routes/connexion.yaml'
    prefix: '/connexion'